### ISSUE TITLE
Module doesn't show up since 0.7.6

### ISSUE THREAD

**Issue by Alivender** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#23]
Hey there.

This is my favourite character sheet for Foundry VTT. Excellent job!
Unfortunately since I upgraded to 0.7.6 a few days ago I can no longer use it, because:

- The module no longer shows up in the module management list, so it cannot be enabled
- The module shows up in the list of installed modules in the setup screen
- The module is present in the UserData/modules folder
- I have re-installed the module and I have disabled all other modules as well.

I thought I'd let you know in case it works for you and you weren't aware of the issue.
Kind regards,
Alivender

**Comment by akrigline** [comment]
@Alivender thanks for the report, what version of the dnd5e system are you using?
The latest version of this sheet is only compatible with dnd5e 0.99 and I believe I set it up so that i cannot be activated without that being true (I'm not certain that's the issue here but it might be).

If you're unwilling to update you dnd5e system version, I'd recommend that you uninstall this sheet and reinstall version 0.8.2 manually with this module.json url:
```
https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/releases/download/v0.8.2/module.json
```

**Comment by Alivender** [comment]
@akrigline Thank you so much for replying. That was exactly the issue. I forgot that the system also needs updating and was still on dnd5e 0.96. I just upgraded to dnd5e 1.1.1 and the character sheet works again.

My players will be as overjoyed as I am that our favourite character sheet is back for the next session. My apologies if I've missed this compatibility information somewhere and thank you again for help and making this module!

**Comment by akrigline** [comment]
Awesome @Alivender, glad I could help! Thanks a million for taking the time to fill out an issue report. If you have any other feature suggestions, etc feel free to open an issue for them.
