### ISSUE TITLE
[QUESTION] Usage without Action Tab?

### ISSUE THREAD

**Issue by Shuggaloaf** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#49]
Just want to say first I love this sheet. I've had Foundry for a little over a month and tried a few sheets and very quickly landed on yours. Players tried others as well and we all love this sheet.

Now I'll preface this by saying none of us have used DnD Beyond or their sheet. That said, after using this for about 6 weeks now, I've found that neither I nor my players use the Action Tab. Any chance there's a way to disable it? I know that the Action List mod is a dependency. If that is uninstalled will it kill the sheet, or would that work to remove it? 

I know we could just ignore it, but I always feel if I can get rid of a mod I'm not using (Action List) then that's always a better solution. Additionally, we use the (Crash's Tracking & Training) Downtime mod and that adds another tab as well, so it gets a little crowded. 

Finally it's obviously not a deal breaker as I think this is still the best sheet around, but I figure it couldn't hurt to ask!

**Comment by akrigline** [comment]
Thanks for your feedback!

I'm not terribly inclined to make the Actions tab an option, but I guess it could be done. 

The Actions List module was split out so I could share its functionality with other modules from a more centralized location. I don't really know if uninstalling it would break anything in the sheet, but I know that activating modules will be mad at you.

Another alternative if you _really_ didn't want that tab to show up would be to use the Custom CSS module to hide it. Since it's the default tab I'm not sure how much that would break, but it's something...

Yeah Idk how to proceed on this. I think I'll close this as 'wontfix' and say something cheesy like "you should really try the actions tab out, especially now that it lets you add favorites to it manually!" :P

**Comment by Shuggaloaf** [comment]
Hey no worries! I figured it may be difficult. And yeah disabling the AL mod just doesn't allow you to use the sheet. 

Just FYI I(we) did try the Actions tab. Don't want you to think I just wrote it off. :-) The feedback, for whatever it's worth, is that the players prefer to keep weapon attacks in the hotbar and use the spellbook tab for spells. The Spell tab has more info and you don't have just 1 long list because everything is separated out nicely by level.

Again though I realize this is just a preference thing. I just wanted to first thank you for the sheet and figured I'd share what others users may also be thinking (especially since it was the _whole_ group and not just 1 or 2 of us). Thanks!
